# Generated by Django 4.0.4 on 2022-05-18 11:22

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', colorfield.fields.ColorField(choices=[('#FFFFFF', 'Branco'), ('#000000', 'Preto'), ('#FF0000', 'Vermelho'), ('#0000ff', 'Azul'), ('#065535', 'Verde'), ('#FFFF00', 'Amarelo'), ('#C0C0C0', 'Cinzento'), ('#FFC0CB', 'Rosa')], default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=50)),
                ('nif', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator('[1-9]\\d*'), django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)])),
                ('email', models.EmailField(max_length=50)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('[1-9]\\d*'), django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13), django.core.validators.MaxValueValidator(9999999999999), django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('recommended_age', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('[1-9]\\d*'), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(3), django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(199)])),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('material_type', models.CharField(max_length=50, null=True)),
                ('article_dimension', models.CharField(max_length=12, null=True)),
                ('box_dimension', models.CharField(max_length=12, null=True)),
                ('care_of_use', models.CharField(max_length=50, null=True)),
                ('box_content', models.CharField(max_length=50, null=True)),
                ('nutriscore', models.CharField(max_length=1, null=True)),
                ('ingredients', models.TextField(blank=True, max_length=300, null=True)),
                ('nutritional_table', models.TextField(blank=True, max_length=300, null=True)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity_unit', models.CharField(choices=[('gr', 'gramas'), ('kg', 'kilogramas'), ('un', 'unidades'), ('pck', 'packs'), ('caps', 'capsulas'), ('doses', 'doses'), ('lt', 'litros'), ('mm', 'milímetros'), ('cm', 'centímetros'), ('prc', 'porções'), ('saq', 'saquetas')], max_length=5)),
                ('seles_unit', models.CharField(choices=[('un', 'unidade'), ('kg', 'kilograma')], max_length=3)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_api.brand')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_api.color')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_api.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_api.supplier'),
        ),
    ]
