# Generated by Django 4.0.4 on 2022-05-18 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_age',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(199)]),
        ),
    ]
