# Generated by Django 4.0.4 on 2022-06-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='descontinuado',
            field=models.BooleanField(default=False),
        ),
    ]
