# Generated by Django 4.0.4 on 2022-05-18 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0002_alter_product_ean_alter_product_recommended_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='platform_api.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_age',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(199)]),
        ),
    ]
