# Generated by Django 4.0.4 on 2022-05-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0003_alter_product_color_alter_product_recommended_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article_dimension',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='box_content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='box_dimension',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='care_of_use',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
