# Generated by Django 4.0.4 on 2022-06-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0004_rename_address_supplier_street_supplier_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bloqueado',
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='door_number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
