# Generated by Django 4.0.4 on 2022-05-18 23:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0004_alter_product_article_dimension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'Branco'), ('#000000', 'Preto'), ('#FF0000', 'Vermelho'), ('#0000ff', 'Azul'), ('#065535', 'Verde'), ('#FFFF00', 'Amarelo'), ('#C0C0C0', 'Cinzento'), ('#FFC0CB', 'Rosa')], default='#FFFFFF', image_field=None, max_length=18, samples=None, unique=True),
        ),
    ]
