# Generated by Django 4.0.4 on 2022-05-19 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0005_alter_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nif',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('[1-9]\\d*'), django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9)]),
        ),
    ]
