# Generated by Django 4.0.4 on 2022-06-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0005_remove_product_bloqueado_product_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seles_unit',
            new_name='sales_unit',
        ),
    ]
