# Generated by Django 4.0.4 on 2022-05-19 12:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0006_remove_supplier_id_alter_supplier_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_api.supplier', verbose_name='fornecedor'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nif',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1)]),
        ),
    ]
