# Generated by Django 4.0.4 on 2022-05-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0007_alter_brand_supplier_alter_supplier_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_api.supplier'),
        ),
    ]
