# Generated by Django 4.0.6 on 2022-07-12 20:51

from django.db import migrations, models
import platform_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0007_remove_product_id_alter_product_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=platform_api.models.upload_product_image_to),
        ),
    ]
