# Generated by Django 4.0.6 on 2022-07-12 23:50

from django.db import migrations, models
import platform_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_api', '0008_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=platform_api.models.upload_supplier_image_to),
        ),
    ]
